
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORI = 13;
  public static final int PUNCOM = 16;
  public static final int CORD = 14;
  public static final int PARI = 18;
  public static final int FLECHA = 15;
  public static final int PARD = 19;
  public static final int OPERA = 3;
  public static final int TK_DIFERENCIA = 10;
  public static final int DOSP = 12;
  public static final int ID = 5;
  public static final int NUM = 6;
  public static final int UNIVERSO = 7;
  public static final int COMA = 17;
  public static final int EOF = 0;
  public static final int TK_COMPLEMENTO = 11;
  public static final int CONJ = 2;
  public static final int TK_INTERSECCION = 9;
  public static final int error = 1;
  public static final int EVALUAR = 4;
  public static final int TK_UNION = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "OPERA",
  "EVALUAR",
  "ID",
  "NUM",
  "UNIVERSO",
  "TK_UNION",
  "TK_INTERSECCION",
  "TK_DIFERENCIA",
  "TK_COMPLEMENTO",
  "DOSP",
  "CORI",
  "CORD",
  "FLECHA",
  "PUNCOM",
  "COMA",
  "PARI",
  "PARD"
  };
}

